In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [2]:
def flatten(l):
    newl = []
    for i in l:
        if type(i) == list:
            for j in i:
                newl.append(j)
        else:
            newl.append(i)
    return newl


In [3]:
def get_binary_repr(x, n):
    l = '0' + str(len(format(n, 'b'))) + 'b'
    return format(x, l)

In [4]:
def get_subset(pa):
    p = len(pa)
    subset = {}
    for i in range(p+1):
        subset[i] = []
        
    n = 2**p - 1
    
    for i in range(2**p):
        subset_ = []
        x = get_binary_repr(i, n)
        for i in range(len(x)):
            if x[i] == '1':                
                subset_.append(pa[i])
        subset[len(subset_)].append(subset_)
        
    return subset            

In [5]:
def compute_coeff(A,y):
    return np.linalg.inv(A.T @ A) @ A.T @ y

In [6]:
credit = pd.read_csv('./datasets/Credit.csv', sep=',')
credit['Bgender'] = credit['Gender'].map({' Male': 1, 'Female': 0})
credit['Bstudent'] = credit['Student'].map({'No': 0, 'Yes': 1})
credit['isAsian'] = credit['Ethnicity'].replace(['Asian', 'Caucasian', 'African American'], [1, 0, 0])
credit['isCaucasian'] = credit['Ethnicity'].replace(['Asian', 'Caucasian', 'African American'], [0, 1, 0])
credit['isMarried'] = credit['Married'].map({'Yes': 1, 'No': 0})

In [7]:
credit.head(5)

ID   Income  Limit  Rating  Cards  Age  Education  Gender Student Married  \
0   1   14.891   3606     283      2   34         11    Male      No     Yes   
1   2  106.025   6645     483      3   82         15  Female     Yes     Yes   
2   3  104.593   7075     514      4   71         11    Male      No      No   
3   4  148.924   9504     681      3   36         11  Female      No      No   
4   5   55.882   4897     357      2   68         16    Male      No     Yes   

   Ethnicity  Balance  Bgender  Bstudent  isAsian  isCaucasian  isMarried  
0  Caucasian      333        1         0        0            1          1  
1      Asian      903        0         1        1            0          1  
2      Asian      580        1         0        1            0          0  
3      Asian      964        0         0        1            0          0  
4  Caucasian      331        1         0        0            1          1

In [8]:
pa = ['Income', 'Limit', 'Rating', 'Cards', 'Age', 'Education','Bgender',
       'Bstudent', ['isAsian', 'isCaucasian'], 'isMarried']
subset = get_subset(pa)

In [9]:
count = 0
for pa in subset:
    for i in subset[pa]:
        count += 1
        if i != 0:
            y = np.array(credit['Balance'])
            p = flatten(i)
            A = np.column_stack((np.ones(len(y)), credit[p]))
    
            theta = compute_coeff(A, y)
            print(theta)
        else:
            print(credit['Balance'].mean())

[520.015]
[523.29032258  -5.34746544]
[531.         -18.68627451 -12.50251256]
[480.36944444 396.45555556]
[529.53623188 -19.73312308]
[535.96620991  -1.18596356]
[5.17292225e+02 4.89113993e-02]
[434.28610081  28.98694816]
[-390.84634179    2.56624033]
[-2.92790495e+02  1.71637278e-01]
[246.51475059   6.04836341]
[532.98129497 -18.07888657 -12.1523204   -3.77208081]
[471.91662987 398.14611847  13.52450331]
[490.7756954  398.22061555 -29.21557777  -6.29705452]
[532.99925427 -19.80111068  -5.60035652]
[540.91791962 -20.03824577 -19.37088481 -12.65304606]
[483.6410913  -6.654197  395.8455875]
[538.50907748  -1.14788662  -4.98775903]
[547.04243487  -1.18610982 -18.58831297 -12.73213659]
[533.24498452  -3.95331141 399.42053911]
[545.25550293  -1.17004283 -19.69622152]
[ 5.21111570e+02  3.80557331e-02 -5.24904164e+00]
[ 5.29818910e+02  2.05388866e-02 -1.86124724e+01 -1.24644790e+01]
[4.66120901e+02 2.55172401e-01 3.96892893e+02]
[ 5.26938239e+02  4.66138964e-02 -1.97266696e+01]
[ 5.33213459e

[-403.71006659    2.57187       2.93987332  -13.20157024  -36.41797675]
[-436.84823883    2.57069744    2.61744993  -12.20279069   31.16742515
   14.38259391]
[-4.29923577e+02  2.56775283e+00 -1.21724702e-01  5.18061296e-01
  3.99276213e+02]
[-257.37001601    2.60224031   -2.40412128   30.94948661   13.97326994
  -44.51682871]
[-304.41987207    2.59566918   -2.19587767  392.56845052  -22.67717564]
[-333.73771545    2.59371938   -2.1237747   395.74773866   14.15740034
   16.4387459 ]
[-234.03966125    2.59885359   -2.44464887  -13.4425877   -42.13696779]
[-276.85774533    2.59496517   -2.31808337  -12.49930022   23.52053759
    9.83093397]
[-3.20405474e+02  2.59246666e+00 -2.14447149e+00  1.60551849e-01
  3.95502574e+02]
[-281.9436054     2.60125637   -2.44903823    3.07196801  -42.96729111]
[-320.20699854    2.5970153    -2.31992157    2.7001339    23.75823083
   10.46526888]
[-3.20115087e+02  2.59245260e+00 -2.14446868e+00 -1.54477510e-02
  3.95499433e+02]
[-300.41445013    2.59462605

[-3.43710605e+02  1.72180489e-01  1.11625576e+00  4.03003551e+02
  2.00001864e+01  2.14012035e+01 -1.34504692e+01]
[-3.31828815e+02  1.72149571e-01 -8.41676129e-01  4.03554028e+02
  1.99625889e+01  2.12072220e+01 -1.31650709e+01]
[-3.12822183e+02  1.72120272e-01  2.04675895e+00 -1.21836063e+01
  3.33842857e+01  1.73503003e+01 -3.43684318e+01]
[-3.16251267e+02  1.72000571e-01 -9.06652972e-01  9.55649504e-01
  4.03764676e+02 -1.12697543e+01]
[-3.37560602e+02  1.72049527e-01 -9.56831698e-01  1.35121761e+00
  4.05473633e+02  1.78202530e+01  1.99874544e+01]
[-2.26462151e+02  1.73758813e-01 -2.10715414e+00  3.98914812e+02
  1.37938367e+01  1.81664749e+01 -1.88111218e+01]
[-155.95200405    0.17380669   -2.34030914  -12.54674294   26.40876155
   13.34603716  -39.43324133]
[-2.13482116e+02  1.73667662e-01 -2.12460005e+00  4.61418903e-01
  3.98691167e+02 -1.75412968e+01]
[-2.38393193e+02  1.73590639e-01 -2.06906864e+00  8.48965567e-01
  4.01499796e+02  1.08162989e+01  1.65115217e+01]
[-1.9152273

  8.98690147e-01  4.02132739e+02  1.08694895e+01  1.63537442e+01]
[-4.26691908e+02  1.71997128e-01  2.83256262e+01 -5.42680078e-01
  4.06418172e+02  1.93321989e+01  2.16008624e+01 -1.24601578e+01]
[-4.23758084e+02  1.71990635e-01  2.82956046e+01 -2.33056302e-01
  4.06645063e+02  1.93480242e+01  2.15536968e+01 -1.23700035e+01]
[-3.97371350e+02  1.71968899e-01  2.63077936e+01  2.63468351e+00
 -1.38500145e+01  3.28560092e+01  1.76343424e+01 -3.37960758e+01]
[-4.07261750e+02  1.71842054e-01  2.82926834e+01 -2.99121389e-01
 -7.24438338e-01  4.06616825e+02 -1.05519197e+01]
[-4.28486624e+02  1.71892697e-01  2.83415150e+01 -3.37850857e-01
 -3.57524980e-01  4.08305382e+02  1.72814043e+01  2.03936451e+01]
[-3.08263148e+02  1.73644683e-01  2.94462040e+01 -2.20403989e+00
  4.02439661e+02  1.28673933e+01  1.82394219e+01 -1.80026690e+01]
[-2.30303874e+02  1.73698024e-01  2.72754141e+01 -2.43222082e+00
 -1.42692813e+01  2.55993168e+01  1.33625145e+01 -3.88695824e+01]
[-2.94635951e+02  1.73555485e-01 

  415.14189721   21.42369234   10.65354753  -15.4145555 ]
[-480.67848312   -7.5424709     3.94336279    2.10736093   -0.92954029
   -3.18827665   34.90679088    5.98704866  -37.11079245]
[-553.15529404   -7.7699557     3.97618268    4.07374283   -0.67054713
   10.3420098   417.11666271  -13.40301956]
[-574.7968356    -7.78219655    3.97816577    4.05632612   -0.61020076
   10.90192029  418.227138     19.32613481    9.37615848]
[-518.04185988   -7.53915602    3.94448185    2.38044469   -0.93564906
    2.60176963   34.94058611    6.60367257  -37.92521916]
[-5.42954750e+02 -7.76226771e+00  3.97429024e+00  4.12986650e+00
 -6.73195993e-01 -3.56858285e-01  4.16411674e+02 -1.34597577e+01]
[-5.62258839e+02 -7.77434171e+00  3.97610949e+00  4.10313952e+00
 -6.13064424e-01 -4.93551840e-01  4.17589545e+02  1.89875483e+01
  9.18758289e+00]
[-502.97459216   -7.52152464    3.93783622    2.55629609   -0.98426508
    2.68952758   -4.03218791  -35.24624148]
[-535.33225136   -7.55589884    3.94128099    

In [12]:
count

1024